# Generated by Django 2.2.2 on 2019-06-18 19:39

import cars.models.car
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='brand')),
                ('model', models.CharField(max_length=64, verbose_name='model')),
                ('year', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1920), cars.models.car.max_value_current_year], verbose_name='year')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
    ]
